# Generated by Django 4.1.7 on 2023-02-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название авто: ')),
                ('name_user', models.CharField(max_length=20, verbose_name='Ваше имя: ')),
                ('number_user', models.IntegerField(verbose_name='Контактный телефон: ')),
                ('cost', models.IntegerField(verbose_name='Стоимость авто: ')),
                ('year', models.IntegerField(verbose_name='Год выпуска: ')),
                ('content', models.TextField(verbose_name='Описание авто: ')),
                ('photo', models.ImageField(upload_to='all_photos/%Y/%m/%d/')),
                ('city', models.CharField(max_length=20, verbose_name='Продажа в городе: ')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
