# Generated by Django 4.1.7 on 2023-02-20 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_post_content_alter_post_cost_alter_post_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='car_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Марка авто '),
        ),
        migrations.AddField(
            model_name='post',
            name='car_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Модель авто '),
        ),
        migrations.AddField(
            model_name='post',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Продажа в городе '),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
