# Generated by Django 4.1.7 on 2023-02-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_tag_tag_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
